### ISSUE TITLE
Decide upon DB tables

### ISSUE THREAD

**Issue by CalleFreme** [Frazz3/DH2642_Project_TRAVELUP#11]

**Comment by stinalangstrom** [comment]
## Nuvarande
**Restaurants:**
* id
* name
* price
* description
* location_id

**Activities**
* id
* name
* price
* description
* location_id

**Comment by stinalangstrom** [comment]
## Ny

**Restaurants:**
* id
* name
* price
* description
* location_id
* **cuisine (a list)**
* **website**
* **photo**

**Activities**
* id
* name
* price
* description
* location_id
* **photo**
* **website**
